### PR TITLE
New framwork pygame implementation

### PR DESCRIPTION
**Pull request by badhon1512**
Here, I have added a new framework pygame.

### CODE REVIEW

**Comment by ScheiklP** [comment]
Hi @badhon1512,
thanks for the PR!
I have made some changes and pushed them to a branch of the same name in this repo.

Could you merge these changes into your branch to update the PR?

There are two further TODOs:
1. RenderMode.HEADLESS is currently not working for RenderFramework.PYGAME
2. Could you implement the get_depth_from_pygame function? It is added with a NotImplemented tag in the new branch.

Cheers,
Paul

**Comment by badhon1512** [comment]
Hi @ScheiklP,

Thank you for your message and for reviewing the pull request. I have received your changes and have started working on them. I have taken note of the two additional tasks you mentioned.

Thank you for bringing these tasks to my attention. I will address them promptly and update the pull request accordingly.

Best regards,
Badhon

**Comment by badhon1512** [comment]
Hi @ScheiklP ,
I have completed the previous tasks assigned to me(2 to-do tasks), and after testing, everything appears to be functioning correctly. I would appreciate it if you could review my code and provide any feedback or suggestions you may have.

Best regards,
Badhon

**Comment by ScheiklP** [comment]
Hi @badhon1512,
I have made some final changes and pushed them to a branch of the same name in this repo.
Could you merge these changes into your branch to update the PR?

Cheers,
Paul

**Comment by badhon1512** [comment]
Hi @ScheiklP ,
I have merged your branch into mine, and the pull request has been updated.

Cheers,
Badhon

**Pull request merged**
